#!/usr/bin/env bash

case "$1" in
    rebase)
        if [[ "$(uname -s)" = Darwin ]]; then
            osascript <<EOF
            display notification "git-ctags: `pwd`" with title "post-rewrite"
EOF
        fi
        ~/bin/git-ctags &>/dev/null &
        ;;
esac
