#!/usr/bin/zsh

export TERM=rxvt-256color
export EDITOR=vim
export MANPAGER="/bin/sh -c \"col -b | vim -c 'set ft=man' -\""
export AWT_TOOLKIT=MToolkit  # bugfix for dwm and AWT/Swing
export NNTPSERVER=news.fu-berlin.de
export PLAN9=/data/repo/plan9port
export STUDIO_JDK=/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk

if [[ `uname -s` == 'Darwin' ]]; then
    export GOPATH=/data/go GOARCH=amd64 GOOS=darwin
    export NODE_PATH=/usr/local/lib/node_modules
else
    export GOPATH=/data/go GOARCH=amd64 GOOS=linux
fi

# $PLAN9/bin
# $GOPATH/bin

for dir in \
    /sbin \
    /usr/local/opt/coreutils/libexec/gnubin \
    /usr/local/lib/node_modules/coffee-script/bin \
    $HOME/.cabal/bin \
    /data/languages/go/bin \
    $HOME/local/*/bin \
    $HOME/bin
do
    [[ -d $dir ]] && path=($dir $path)
done

for dir in \
    /usr/local/opt/coreutils/libexec/gnuman
do
    [[ -d $dir ]] && manpath=($dir $path)
done
